<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="spacer_side">
    
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
            <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
                
                <div class="nl_wrap">
                <span class="nl_ttl">newsletter:</span>
                <input name="email" type="email" id="newsletter"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
                
                <input type="submit" value="ok">
                
                    <div class="clearfix"></div>
                </div>
            </form>
        </div>
        
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
            <div class="nl_wrap">
            <span class="nl_ttl">follow us:</span>
            <ul class="follow list-inline list-unstyled">
                <li><a class="icon fb" href="javascript:void(0);"></a></li>
                <li><a class="icon twt" href="javascript:void(0);"></a></li>
                <li><a class="icon in" href="javascript:void(0);"></a></li>
            </ul>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
</div>