<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
?>
<div class="spacer_side">
    <div class="br_collection">
        <div class="container-fluid">
    <div class="row">
                <div class="col-lg-12"> 
                    <span class="brc_ttl">AMBROSIA COLLECTION</span>
                    <p class="brc_text">This text outlines the values of no parabens, no animal testing, no animal products... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lectus mauris, luctus tincidunt sagittis condimentum, convallis sed magna. Sed ultrices diam porta lorem imperdiet blandit. </p>
                </div>
            </div>
            <div class="row">

    
        
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>

                <ol class="products list items product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">' : '</li><li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">' ?>
                        <div class="brc_product_wrap">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product brc_pr_img photo product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                            <div class="brc_pr_desc product details product-item-details">
                                <div class="desc_row1 desc_row">
                    <div class="desc_left">
                    
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <span class="pr_nm"><?php echo $block->escapeHtml($_item->getName()) ?></span>
                                    </a>
                                
                    </div>
                    <div class="desc_right">
                    			<div class="brc_price"><?php echo $block->getProductPriceHtml($_item, $type); ?></div>
                                <?php if ($showCart): ?>
                                            <div class="add_crt">
                                                 <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart"
                                                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <a href="javascript:void(0);"></a>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart"
                                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <a href="javascript:void(0);"></a>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?> 
                                                
                                                
                            
                        
                                            </div>
                                        <?php endif; ?>
                    </div>
                    </div>
                                
                               <div class="desc_row2 desc_row">
                    <div class="desc_left">
                        <span class="pr_rate">rate this product</span>
                    </div>
                    <div class="desc_right">
                    <?php if ($showWishlist): ?>
                                            <div class="wish_list" data-role="add-to-links">
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                       class="action" data-action="add-to-wishlist"
                                                       title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                        <span><?php /* @escapeNotVerified */ //echo __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                
                                            </div>
                                        <?php endif; ?>
                    </div>
                    </div>

                                
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>

        
    </div></div></div></div>
<?php endif;?>
