<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="spacer_side">
<div class="thanks_box">
<div class="container-fluid">
<span class="strip_title">Thank you For your order!</span>
<div class="ord_if n_ord">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <span><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></span>
        <?php  else :?>
             <span><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?> </span>
        <?php endif;?>
             <span><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking info.') ?> <span>
    <?php endif;?>

    <?php echo $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue button" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div></div>
</div></div>