<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Bag'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="si_box">

    <div class="si_left"><span class="si_ttl">shipping information</span></div>
    <div class="si_right">
        <?php if ($block->shouldRenderQuantity()): ?>
        <ul class="list-inline list-unstyled si_list">
        <li>
                             <span class="si_size">40ml</span>
                         </li>
                         <li>
        <span class="qty_lbl">qty</span>
               <div class="spn_wrapper">
               <div class="input-group spinner">
                <input type="text"
                       name="qty"
                       id="qty" class="number"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" 
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            		<div class="input-group-btn-vertical">
                                        <button type="button" class="btn btn-default"><i class="caret-up"></i></button>
                                        <button type="button" class="btn btn-default"><i class="caret-down"></i></button>
                                    </div>
                                </div>
                                </div>
                                <div class="clearfix"></div>
                                </li>
        <?php endif; ?>
       		<li>
       		<div class="actions">
            <input type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="atb action primary tocart"
                    id="product-addtocart-button" />
                
            </li>
            </div>
            <?php echo $block->getChildHtml('', true) ?>
        </ul>
    </div>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magento_Catalog/js/catalog-add-to-cart'
    ], function ($) {
        'use strict';

        $('#product_addtocart_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit: false
                });

                widget.catalogAddToCart('submitForm', $(form));

                return false;
            }
        });
    });
</script>
<?php endif; ?>